NUMPY
DESIGNED FOR FAST NUMERICAL COMPUTING
FUNDAMENTAL PACKAGE FOR SCIENTIFIC COMPUTING IN PYTHON

Ndarray (n dimensional arrays) in numpy are many times faster than python lists.
NUMPY uses C , python calls C code behind the scenes.

Python lists -> flexible and slow
Np arrays ->  homogeneous and optimized with C (faster), efficient in storage and speed, maths, supports direct vectorized operations

Operations on  numpy arrays:
1. Reshaping
2. Indexing (1D AND 2D ARRAYS)
3. Fancy and boolean indexing
4. Slicing

Common datatypes in numpy
1. integer: int32, int64
2. floating point nums: float32, float64
3. boolean: bool
4. complex nums: complex64, complex128
5. string s (byte-str) and u (unicode-str)
6. objects : generic python objects - object

In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr, type(arr))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [3]:
# EXECUTION PERFORMANCE
size = 1_000_000

#PYTHON LIST
py_list = list(range(size))
start = time.time()
sq_list = [number**2 for number in py_list]
end = time.time()
print(f"TIME FOR PYTHON LIST = {end-start} seconds")

#NUMPY ARRAYS
np_array = np.array(py_list)
start = time.time()
sq_array = np_array ** 2
end = time.time()
print(f"TIME FOR NUMPY ARRAYS = {end-start} seconds")

TIME FOR PYTHON LIST = 0.08027863502502441 seconds
TIME FOR NUMPY ARRAYS = 0.01496744155883789 seconds


In [4]:
# MEMORY
import sys

print(f"PYTHON LIST SIZE = {sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"NP ARRAY SIZE = {np_array.nbytes} bytes")  #contiguous memory, reduced overhead (metadata is less)

PYTHON LIST SIZE = 8000056000000 bytes
NP ARRAY SIZE = 8000000 bytes


In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5,"AADITYA"])
print(arr1, type(arr1), arr1.shape, arr1.dtype)
print(arr2, type(arr2), arr2.shape, arr2.dtype)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,) int64
['1' '2' '3' '4' '5' 'AADITYA'] <class 'numpy.ndarray'> (6,) <U21


In [6]:
# 2D ARRAYS
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [7]:
array1 = np.zeros((2,3), dtype="int64") #PREFILL WITH ZEROS
print(array1, array1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [8]:
array2 = np.ones((4,5)) #PREFILL WITH ONE
print(array2, array2.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (4, 5)


In [9]:
array3 = np.full((6,7), 100) #PREFILL WITH 100 (VAL)
print(array3)

[[100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100]]


In [10]:
array4 = np.eye(3) #IDENTITY MATRIX
print(array4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
array5 = np.arange(1,10,2) #RANGE ELEMENTS
print(array5)

[1 3 5 7 9]


In [12]:
array6 = np.linspace(1,100,4) #EVENLY SPACED ARRAYS
print(array6, array6.shape)

[  1.  34.  67. 100.] (4,)


In [13]:
#PROPERTIES
ARRAY = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ARRAY.shape)
print(ARRAY.size)
print(ARRAY.dtype)
print(ARRAY.ndim) # NUMBER OF DIMENSIONS

(3, 3)
9
int64
2


In [14]:
float_array = ARRAY.astype(np.float64)
print(float_array, float_array.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [15]:
# DATA TYPES
arr = np.array([1,2,3.14,4,5])
print(arr, arr.dtype)

[1.   2.   3.14 4.   5.  ] float64


In [18]:
arr1 = np.array([1+3j])   # COMPLEX NUMBERS
arr2 = np.array([4+7j])

print(arr1+arr2)
print(arr1-arr2)
print(arr1.dtype)

[5.+10.j]
[-3.-4.j]
complex128


In [19]:
arr = np.array(["prime", {1,2,3,4,5}, 3.14])
print(arr, arr.dtype)

['prime' {1, 2, 3, 4, 5} 3.14] object
