In [1]:
import numpy as np
# OPERATIONS ON ARRAYS
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)
print("---------------")
reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
---------------
[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [2]:
flattened = arr.flatten() # 2D TO 1D
print(flattened, flattened.shape)

[1 2 3 4 5 6] (6,)


In [3]:
# INDEXING
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

3


In [4]:
# FANCY INDEXING
arr = np.array([1,2,3,4,5,6,7,8,9])
idx = [0, 1, 3]
print(arr[idx])

[1 2 4]


In [5]:
# BOOLEAN INDEXING
arr = np.array([1,2,3,4,5])

print(arr[arr>2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [6]:
# SLICING
arr = np.array([1,2,3,4,5])
print(arr[1:4]) # [start, stop, step]
print(arr[1:])
print(arr[:4])
print(arr[::2])

#python -> creates copy for slicing
#numpy -> view

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [7]:
# COPY VS VIEW
nums = [1,2,3,4,5]
sublist = nums[1:3]
print(sublist)
sublist[0] = 200
print(sublist)
print(nums)

arr = np.array([1,2,3,4,5])
subarray = arr[1:3]
print(subarray)
subarray[0] = 200
print(subarray)
print(arr)

arr = np.array([1,2,3,4,5])
subarray = arr[1:3].copy()
print(subarray)
subarray[0] = 200
print(subarray)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]
[2 3]
[200   3]
[1 2 3 4 5]


AXES IN MULTI-DIMENSIONAL ARRAYS

images -> BLACK AND WHITE -> 2d array (VALUES 0 - 255)
COLOURED IMAGES -> RGB values -> 3d array (VALUES Like 0,255,255)

1D = 1 AXIS (axis 0)
2D = 2 AXES (axis 0 -> rows, axis 1 -> columns)
3D = 3 AXES (axis 0 -> depth or layers, axis 1 -> row in each layer, axis 2 -> column)


In [8]:
# MULTIDIMENSIONAL ARRAYS
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D)
print("------------------------------")
print(np.sum(arr2D))
print("------------------------------")
sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)
print("------------------------------")
sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)
print("------------------------------")
print(arr2D[0:2,1:2])
print("------------------------------")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
45
------------------------------
[12 15 18]
------------------------------
[ 6 15 24]
------------------------------
[[2]
 [5]]
------------------------------


In [9]:
# 3D ARRAY
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[6,5],[5,3]]])
print(arr3D, arr3D.shape)
print("------------------------------")
#indexing
print(arr3D[1,1,0])
print("------------------------------")
#slicing
print(arr3D[:,0,:]) #first row from both layers
print("------------------------------")
print(arr3D[:,:,0]) #first column from both layers
print("------------------------------")
arr3D[:,:,0] = 99
print(arr3D)

[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [6 5]
  [5 3]]] (2, 3, 2)
------------------------------
6
------------------------------
[[1 2]
 [7 8]]
------------------------------
[[1 3 5]
 [7 6 5]]
------------------------------
[[[99  2]
  [99  4]
  [99  6]]

 [[99  8]
  [99  5]
  [99  3]]]


VECTORIZARION : PROCESSES ARE PERFORMED ON THE NP ARRAYS AS WHOLE AND NO NEED OF LOOPS LIKE PYTHON LISTS

In [10]:
# VECTORIZATION
arr = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])
print(arr ** 2)
print(arr + 10)
print(arr + arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[6 6 6 6 6]


BROADCASTING : SCALING ARRAYS WITHOUT USING EXTRA MEMORY

In [11]:
# BROADCASTING
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr1.shape)
print(arr2.shape)

print(arr1+arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


VECTOR NORMALIZATION : NORMALIZATION AN ARRAY MEANS TRANSFORMING ITS VALUES SO THEY FIT INTO A SPECIFIC SCALE OR RANGE

standard normalization : (value - mean) / standard deviation

In [12]:
# normalize
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
std = np.std(arr)
normalized_arr = (arr - mean) / std
print(normalized_arr)

# mean = (1+2+3+4)/4 = 2.5

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


MATHEMATICAL FUNCTIONS

In [13]:
# Aggregation functions
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) #index of min
print(np.argmax(arr)) #index of max
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [14]:
# Power functions
arr = np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [15]:
# Log and exponential functions
arr = np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [16]:
# Rounding values
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.95))
print(np.trunc(3.6778))

arr = np.array([1,2,-3,-4,4,3,-2,1])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr)) #makes negative values positive

3.0
4.0
3.0
3.0
[-4 -3 -2  1  2  3  4]
[-4 -3 -2  1  1  2  3  4]
[1 2 3 4 4 3 2 1]
